### ISSUE TITLE
Sky Go

### ISSUE THREAD

**Issue by Neiljclements** [n00neimp0rtant/xCon-Issues#534] opened 2015-10-18 07:24 UTC
Hello, once upon a time, Xcon used to make the Sky Go app work. Sadly, this is now not the case and if you try and watch a program on the Sky Go app it states it 'won't run on Jailbroken devices'.
I seem to remember you had to install Xcon and a cracked version of the Sky Go app, which you downloaded from your repo. Are there please any plans to do this again?
I know there are probably thousands of people, including myself, who would be extremely grateful if you could recreate this feat of genius?
Kind regards,
Neil

**Comment by Neiljclements** [comment] 2015-10-18 07:26
I meant to add, this means I can't jailbreak my iPad, because I watch Sky Go on it pretty much constantly.
Thank again!!

**Comment by Lunat1k** [comment] 2015-10-19 19:20
Duplicate of #55

**Closed by Lunat1k** 2015-10-19 19:20 UTC

**Comment by Neiljclements** [comment] 2015-10-19 19:23
My apologies dude! Should engage brain and eyes before keyboard.
