### ISSUE TITLE
Ziggo TV

### ISSUE THREAD

**Issue by Lastminuteguy** [n00neimp0rtant/xCon-Issues#278] opened 2013-07-24 00:06 UTC
First of all, my thanks for all the work you've done. I'm a big fan.

Remember #75 ? They've found a way to bypass xcon. 

Could you take a peek in the new version? I've added a cracked version in the link below. Would you be so kind to erase the link after you've downloaded the cracked version?

Thanks.
https://www.dropbox.com/s/9jungcwosd4jer9/Ziggo%20TV-v59.ipa

**Comment by DL-Zeratul** [comment] 2015-02-27 13:53
Why are you opening a new issue if there is already #75?

**Comment by Lastminuteguy** [comment] 2015-02-27 13:59
Isn't your comment a bit late and irrelevant by now?

**Comment by Lunat1k** [comment] 2015-03-24 20:55
Duplicate of #75

**Closed by Lunat1k** 2015-03-24 20:55 UTC
