### ISSUE TITLE
Barclays mobile banking 

### ISSUE THREAD

**Issue by DJ7932** [n00neimp0rtant/xCon-Issues#382] opened 2014-04-25 10:51 UTC
Hi

After the ipad barclays app update to version 1.6on 7.0.6 Jailbroken Ipad, the Xcon beta 37 doesent work.

Has anyone got the barclays app 1.4 for IPAD by anychance? Please upload it or if anyone has a workaround.

**Comment by Lunat1k** [comment] 2015-03-24 21:01
Closing - Duplicate of #61

**Closed by Lunat1k** 2015-03-24 21:01 UTC
