### ISSUE TITLE
Ziggo app detecting jb

### ISSUE THREAD

**Issue by Emptyless** [n00neimp0rtant/xCon-Issues#457] opened 2015-02-05 10:46 UTC
Dutch ziggo app still detecting jailbreak in latest xcon beta

**Comment by dnogwat** [comment] 2015-02-06 15:21
Indeed! The ziggo tv app has been updated some days ago. Now xcon doesn't work anymore, please release an update!

**Comment by DL-Zeratul** [comment] 2015-02-27 13:54
Why are you opening a new issue? There is already #75.

**Comment by Lunat1k** [comment] 2015-03-24 20:55
Duplicate of #75

**Closed by Lunat1k** 2015-03-24 20:55 UTC
